### ISSUE TITLE
icon issue

### ISSUE THREAD

**Issue by delavanty** [robot256/shipping-containers#3]
![20221211163934_1](https://user-images.githubusercontent.com/68756496/206930357-872c5976-5ebb-4313-84a0-7cba593f7107.jpg)

**Comment by robot256** [comment]
Can you please post a factorio.log of the crash so I can reproduce and fix this? Thanks for the report.

**Comment by robot256** [comment]
I can't figure out which mod is creating a belt entity with such a unique layered icon that it breaks my code.  I can look into it if you can post your mod list that causes the crash. Thanks.

**Comment by robot256** [comment]
I attempted to fix this in 0.0.5.  It will log the offending values, so please submit a factorio-current.log the next time you try the mods that caused the problem. Thanks.

**Comment by robot256** [comment]
Marking this resolved.  If it happens again, please post factorio-current.log from right after the error happens.
